 --   Quentin TRIDON
 --   BTS SN2 LYCEE DU GRESIVAUDAN DE MEYLAN
 --   Projet Audiosa
 --   Création de la base de données

-- MySQL Script generated by MySQL Workbench
-- 04/08/16 21:36:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AUDIO_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AUDIO_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AUDIO_DB` DEFAULT CHARACTER SET utf8 ;
USE `AUDIO_DB` ;

-- -----------------------------------------------------
-- Table `AUDIO_DB`.`UTILISATEUR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AUDIO_DB`.`UTILISATEUR` (
  `idUTILISATEUR` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`idUTILISATEUR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AUDIO_DB`.`PLAYLISTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AUDIO_DB`.`PLAYLISTS` (
  `idPLAYLIST` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `items_count` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idPLAYLIST`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AUDIO_DB`.`GENRES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AUDIO_DB`.`GENRES` (
  `idGENRES` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL DEFAULT 'Genre',
  `image` VARCHAR(45) NOT NULL DEFAULT 'default.jpg',
  PRIMARY KEY (`idGENRES`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AUDIO_DB`.`PISTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AUDIO_DB`.`PISTES` (
  `idPISTES` INT NOT NULL AUTO_INCREMENT,
  `genre` INT NOT NULL DEFAULT 1,
  `cover` VARCHAR(255) NOT NULL DEFAULT 'defaultCover.jpg',
  `md5` VARCHAR(45) NOT NULL,
  `filename` VARCHAR(255) NOT NULL,
  `title` VARCHAR(45) NULL,
  `version` FLOAT NULL,
  `album` VARCHAR(45) NULL,
  `tracknumber` INT NULL,
  `artist` VARCHAR(45) NULL,
  `performer` VARCHAR(45) NULL,
  `copyright` VARCHAR(260) NULL,
  `license` VARCHAR(260) NULL,
  `organisation` VARCHAR(45) NULL,
  `description` TINYTEXT NULL,
  `date` INT NULL,
  `location` VARCHAR(45) NULL,
  `contact` VARCHAR(45) NULL,
  `isrc` INT NULL,
  `duree` INT NULL,
  PRIMARY KEY (`idPISTES`, `genre`),
  INDEX `fk_PISTES_GENRES1_idx` (`genre` ASC),
  CONSTRAINT `fk_PISTES_GENRES1`
    FOREIGN KEY (`genre`)
    REFERENCES `AUDIO_DB`.`GENRES` (`idGENRES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AUDIO_DB`.`CONTENU_PLAYLISTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AUDIO_DB`.`CONTENU_PLAYLISTS` (
  `idCONTENU_PLAYLIST` INT NOT NULL AUTO_INCREMENT,
  `PLAYLIST_idPLAYLIST` INT NOT NULL,
  `PISTES_idPISTES` INT NOT NULL,
  PRIMARY KEY (`idCONTENU_PLAYLIST`, `PLAYLIST_idPLAYLIST`, `PISTES_idPISTES`),
  INDEX `fk_PLAYLIST_has_PISTES_PISTES1_idx` (`PISTES_idPISTES` ASC),
  INDEX `fk_PLAYLIST_has_PISTES_PLAYLIST_idx` (`PLAYLIST_idPLAYLIST` ASC),
  CONSTRAINT `fk_PLAYLIST_has_PISTES_PLAYLIST`
    FOREIGN KEY (`PLAYLIST_idPLAYLIST`)
    REFERENCES `AUDIO_DB`.`PLAYLISTS` (`idPLAYLIST`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLAYLIST_has_PISTES_PISTES1`
    FOREIGN KEY (`PISTES_idPISTES`)
    REFERENCES `AUDIO_DB`.`PISTES` (`idPISTES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Création du genre par défaut

INSERT INTO `audio_db`.`genres` (`idGENRES`, `nom`, `image`) VALUES (NULL, 'Genre', 'default.jpg');

-- Création des utilisateurs

CREATE USER 'db_reader_user'@'localhost' IDENTIFIED BY 'VpuCdvqjwNU3ce5T';
CREATE USER 'db_reader_music'@'localhost' IDENTIFIED BY 'qsZuJe6hruAm9nBs';
CREATE USER 'db_writer_music'@'localhost' IDENTIFIED BY '5VHKUmhKrsSspmjs';

-- Attribution des droits de "db_reader_music"

GRANT SELECT ON Audio_db.contenu_playlists TO 'db_reader_music'@'localhost';
GRANT SELECT ON Audio_db.genres TO 'db_reader_music'@'localhost';
GRANT SELECT ON Audio_db.pistes TO 'db_reader_music'@'localhost';
GRANT SELECT ON Audio_db.playlists TO 'db_reader_music'@'localhost';

-- Attribution des droits de "db_writer_music"

GRANT ALTER, INSERT, DELETE, SELECT ON Audio_db.contenu_playlists TO 'db_writer_music'@'localhost';
GRANT ALTER, INSERT, SELECT ON Audio_db.genres TO 'db_writer_music'@'localhost'; 
GRANT ALTER, INSERT, UPDATE ON Audio_db.pistes TO 'db_writer_music'@'localhost';
GRANT ALTER, INSERT, UPDATE, DELETE? SELECT ON Audio_db.playlists TO 'db_writer_music'@'localhost';
GRANT SELECT, UPDATE ON Audio_db.utilisateur TO 'db_writer_music'@'localhost';

-- Attribution des droits de "db_reader_user"

GRANT SELECT ON Audio_db.utilisateur TO 'db_reader_user'@'localhost';
GRANT SELECT ON Audio_db.playlists TO 'db_reader_user'@'localhost';