-- MySQL Script generated by MySQL Workbench
-- 01/14/16 15:09:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AUDIO_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AUDIO_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AUDIO_DB` DEFAULT CHARACTER SET utf8 ;
USE `AUDIO_DB` ;

-- -----------------------------------------------------
-- Table `AUDIO_DB`.`UTILISATEURS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AUDIO_DB`.`UTILISATEURS` (
  `idUTILISATEURS` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`idUTILISATEURS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AUDIO_DB`.`PLAYLISTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AUDIO_DB`.`PLAYLISTS` (
  `idPLAYLIST` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `items_count` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idPLAYLIST`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AUDIO_DB`.`CRITERES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AUDIO_DB`.`CRITERES` (
  `idCRITERES` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `description` TINYTEXT NULL,
  PRIMARY KEY (`idCRITERES`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AUDIO_DB`.`PISTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AUDIO_DB`.`PISTES` (
  `idPISTES` INT NOT NULL AUTO_INCREMENT,
  `crtitère` INT NOT NULL,
  `filename` VARCHAR(260) NOT NULL,
  `title` VARCHAR(45) NULL,
  `version` FLOAT NULL,
  `album` VARCHAR(45) NULL,
  `track_number` INT NULL,
  `artist` VARCHAR(45) NULL,
  `performer` VARCHAR(45) NULL,
  `copyright` VARCHAR(260) NULL,
  `license` VARCHAR(260) NULL,
  `organisation` VARCHAR(45) NULL,
  `description` TINYTEXT NULL,
  `gender` VARCHAR(45) NULL,
  `date` DATETIME NULL,
  `location` VARCHAR(45) NULL,
  `contact` VARCHAR(45) NULL,
  `isrc` INT NULL,
  `cover` VARCHAR(260) NULL,
  PRIMARY KEY (`idPISTES`, `crtitère`),
  INDEX `fk_PISTES_CRITERES2_idx` (`crtitère` ASC),
  CONSTRAINT `fk_PISTES_CRITERES2`
    FOREIGN KEY (`crtitère`)
    REFERENCES `AUDIO_DB`.`CRITERES` (`idCRITERES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AUDIO_DB`.`CONTENU_PLAYLISTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AUDIO_DB`.`CONTENU_PLAYLISTS` (
  `idCONTENU_PLAYLIST` INT NOT NULL AUTO_INCREMENT,
  `PLAYLIST_idPLAYLIST` INT NOT NULL,
  `PISTES_idPISTES` INT NOT NULL,
  PRIMARY KEY (`idCONTENU_PLAYLIST`, `PLAYLIST_idPLAYLIST`, `PISTES_idPISTES`),
  INDEX `fk_PLAYLIST_has_PISTES_PISTES1_idx` (`PISTES_idPISTES` ASC),
  INDEX `fk_PLAYLIST_has_PISTES_PLAYLIST_idx` (`PLAYLIST_idPLAYLIST` ASC),
  CONSTRAINT `fk_PLAYLIST_has_PISTES_PLAYLIST`
    FOREIGN KEY (`PLAYLIST_idPLAYLIST`)
    REFERENCES `AUDIO_DB`.`PLAYLISTS` (`idPLAYLIST`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLAYLIST_has_PISTES_PISTES1`
    FOREIGN KEY (`PISTES_idPISTES`)
    REFERENCES `AUDIO_DB`.`PISTES` (`idPISTES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AUDIO_DB`.`METADONNEES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AUDIO_DB`.`METADONNEES` (
  `idMETADONNEES` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `version` FLOAT NULL,
  `album` VARCHAR(45) NULL,
  `track_number` INT NULL,
  `artist` VARCHAR(45) NULL,
  `performer` VARCHAR(45) NULL,
  `copyright` VARCHAR(260) NULL,
  `license` VARCHAR(260) NULL,
  `organisation` VARCHAR(45) NULL,
  `description` TINYTEXT NULL,
  `gender` VARCHAR(45) NULL,
  `date` DATETIME NULL,
  `location` VARCHAR(45) NULL,
  `contact` VARCHAR(45) NULL,
  `isrc` INT NULL,
  `cover` VARCHAR(260) NULL,
  PRIMARY KEY (`idMETADONNEES`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
